export const TOKENS = {
  USER_REPO: Symbol.for('USER_REPO'),
  COST_REPO: Symbol.for('COST_REPO'),
  FUND_REPO: Symbol.for('FUND_REPO'),
  INCOME_REPO: Symbol.for('INCOME_REPO'),
  TAG_REPO: Symbol.for('TAG_REPO'),
  WALLET_REPO: Symbol.for('WALLET_REPO'),
  SHARING_RULE_REPO: Symbol.for('SHARING_RULE_REPO'),
  SYNCHRONIZATION_ORDER_REPO: Symbol.for('SYNCHRONIZATION_ORDER_REPO'),
};
